# Generated by Django 2.2.7 on 2020-06-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
    ]
