# Generated by Django 2.2.7 on 2020-07-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200629_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='result',
            field=models.CharField(blank=True, default='0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user1Round1',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user1Round2',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user1Round3',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user1Round4',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user1Total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user2Round1',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user2Round2',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user2Round3',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user2Round4',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user2Total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
