# Generated by Django 2.2.7 on 2020-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200712_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='user1Round1',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user1Round2',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user1Round3',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user1Round4',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user2Round1',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user2Round2',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user2Round3',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user2Round4',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
    ]
